### ISSUE TITLE
如何避免跳动

### ISSUE THREAD

**Issue by xieyilong** [LZY101724/KLineChartDemo#4]
加载K线图完成，移动K线图到左边 1/5个屏幕的位置，右边腾出，类似火币网一样，但是会有滚动跳动的效果

**Comment by LZY101724** [comment]
你说的是左右移动显示k线数据的那个框是吧，那个框和里面的数据都是动态绘制的，数据不一样，框大小也不一样，如果你不想要这种显示效果，你可以在MainDraw这个类的drawSelector()方法里修改你想要的效果就可以了

**Comment by ElivenLZY** [comment]
> 加载K线图完成，移动K线图到左边 1/5个屏幕的位置，右边腾出，类似火币网一样，但是会有滚动跳动的效果

你说的是左右移动显示k线数据的那个框是吧，那个框和里面的数据都是动态绘制的，数据不一样，框大小也不一样，如果你不想要这种显示效果，你可以在MainDraw这个类的drawSelector()方法里修改你想要的效果就可以了

**Comment by xieyilong** [comment]
就是第一次 加载出k线的时候，把K线整体往左边滚动 1/5个屏幕的距离，右边腾出空间 这个时候，会跳动，体验不是很好，这个东东搞了好久，目前是用你的方法scrollby 多少个距离，

在 2018-12-29 11:12:35，"Mr.Liu" <notifications@github.com> 写道：


加载K线图完成，移动K线图到左边 1/5个屏幕的位置，右边腾出，类似火币网一样，但是会有滚动跳动的效果

你说的是左右移动显示k线数据的那个框是吧，那个框和里面的数据都是动态绘制的，数据不一样，框大小也不一样，如果你不想要这种显示效果，你可以在MainDraw这个类的drawSelector()方法里修改你想要的效果就可以了
