### ISSUE TITLE
点击怎么显示那个黑色的弹框

### ISSUE THREAD

**Issue by zhupengxiang** [LZY101724/KLineChartDemo#5]
点击怎么显示那个黑色的弹框

**Comment by ElivenLZY** [comment]
为避免滑动冲突，长按可显示弹框

**Comment by zhupengxiang** [comment]
这个是基于fujianlian/KLineChart的改动的吗  和那个有什么不一样的地方? @LZY101724

**Comment by ElivenLZY** [comment]
1，增加/修改了一些自定义样式
2，对均线值进行动态计算（我们项目的K线图需要不断的加载更多数据到最左边和添加新数据和最右边）

**Comment by zhupengxiang** [comment]
好吧   我看这差不多 就用的fujianlian的那个,你这个里面设置分时图怎么弄  demo里面没有分时图的标签和他那个一样的用法么

**Comment by ElivenLZY** [comment]
我们项目里面没有用到分时图，原项目是有的，我把他注释掉了。我看原项目之前有次更新，你就直接他的吧

**Comment by zhupengxiang** [comment]
好吧   这个分时图建议还是加上的好  大部分应该都有分时

**Comment by ElivenLZY** [comment]
抽时间我加下
